<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        // ── TABLE 1: organizational_records ──────────────────────────────────
        Schema::create('organizational_records', function (Blueprint $table) {
            $table->id();

            // Ownership — same pattern as every other table in Ventiq
            $table->foreignId('organization_id')->constrained()->cascadeOnDelete();
            $table->foreignId('created_by')->constrained('users')->cascadeOnDelete();

            // Optional event link — if present, title + date + venue + attendance
            // are pulled from the event automatically
            $table->foreignId('event_id')->nullable()->constrained()->nullOnDelete();

            // Layer 2: chain records together — "this meeting follows that one"
            // Null for now, used when user selects a previous record as context
            $table->foreignId('parent_record_id')
                ->nullable()
                ->constrained('organizational_records')
                ->nullOnDelete();

            // Record classification — drives AI tone + output format
            $table->enum('record_type', [
                'meeting',        // formal meeting with agenda + resolutions
                'brainstorming',  // ideas session, looser output
                'planning',       // planning session, action-heavy output
                'report',         // operational/status report
                'update',         // ministry/department update
                'committee',      // committee notes with formal resolutions
            ])->default('meeting');

            // Title — nullable because we auto-generate from event name
            // or AI suggests one from the raw input
            $table->string('title')->nullable();

            // When the meeting/session happened — separate from created_at
            $table->date('meeting_date')->nullable();

            // Physical location — nullable, pulled from event if linked
            $table->string('location')->nullable();

            // ── AI processing columns ─────────────────────────────────────────

            // What the user dumped in — preserved forever, never overwritten
            $table->longText('raw_input');

            // What the AI extracted before user confirmation — JSON snapshot
            // Structure: { agenda: [], discussion_points: [], decisions: [],
            //              action_items: [], open_issues: [], suggested_title: "" }
            $table->json('ai_extracted')->nullable();

            // The final formatted document (minutes/summary/report)
            // Generated after user confirms extractions
            $table->longText('final_output')->nullable();

            // Tracks where we are in the flow
            // draft       = user has typed raw input, not yet extracted
            // extracted   = AI has extracted, user reviewing
            // finalized   = user confirmed, final doc generated
            $table->enum('status', ['draft', 'extracted', 'finalized'])->default('draft');

            // Job tracking — same pattern as AiGenerationResult
            // Stores the jobId while async extraction is running
            $table->string('extraction_job_id')->nullable()->index();

            $table->timestamps();
            $table->softDeletes(); // orgs may want to archive, not permanently delete

            // Common queries: all records for an org, records for an event
            $table->index(['organization_id', 'created_at']);
            $table->index(['event_id']);
        });

        // ── TABLE 2: record_extractions ───────────────────────────────────────
        // The 5 structured categories extracted by AI, confirmed by user
        // These are the core intelligence rows — not text in a PDF
        Schema::create('record_extractions', function (Blueprint $table) {
            $table->id();

            $table->foreignId('record_id')
                ->constrained('organizational_records')
                ->cascadeOnDelete();

            // The 5 extraction categories — fixed, no more, no less
            $table->enum('category', [
                'agenda',            // What was discussed
                'discussion_point',  // What was said / debated
                'decision',          // What was concluded / resolved
                'action_item',       // Who must do what (graduates to record_action_items)
                'open_issue',        // What remains unresolved (graduates to record_open_issues)
            ]);

            $table->text('content');

            // Was this generated by AI or manually added by the user after review
            $table->boolean('is_ai_generated')->default(true);

            // Controls display order within each category
            $table->unsignedTinyInteger('display_order')->default(0);

            $table->timestamps();

            // Layer 2 query: "all decisions across all records for this org"
            $table->index(['record_id', 'category']);
        });

        // ── TABLE 3: record_action_items ──────────────────────────────────────
        // Action items graduate from record_extractions into here
        // so they can change state over time (Layer 2 continuity)
        Schema::create('record_action_items', function (Blueprint $table) {
            $table->id();

            $table->foreignId('record_id')
                ->constrained('organizational_records')
                ->cascadeOnDelete();

            // The extraction row this came from — nullable if added manually
            $table->foreignId('extraction_id')
                ->nullable()
                ->constrained('record_extractions')
                ->nullOnDelete();

            $table->text('description');

            // Phase 1: free text name. Phase 2: link to actual user.
            $table->string('assigned_to_name')->nullable();
            $table->foreignId('assigned_to_user_id')
                ->nullable()
                ->constrained('users')
                ->nullOnDelete();

            $table->date('due_date')->nullable();

            $table->enum('status', [
                'pending',
                'in_progress',
                'completed',
                'carried_forward', // Layer 2: appeared in next meeting
            ])->default('pending');

            // Layer 2: links this item back to where it first appeared
            // "John still hasn't submitted quotations from last month"
            $table->foreignId('carried_from_id')
                ->nullable()
                ->constrained('record_action_items')
                ->nullOnDelete();

            $table->timestamps();

            // Layer 2 query: "all pending action items for this org"
            $table->index(['record_id', 'status']);
            $table->index(['assigned_to_user_id', 'status']);
        });

        // ── TABLE 4: record_open_issues ───────────────────────────────────────
        // Open issues graduate from record_extractions into here
        // No owner yet — that's what separates them from action items
        Schema::create('record_open_issues', function (Blueprint $table) {
            $table->id();

            $table->foreignId('record_id')
                ->constrained('organizational_records')
                ->cascadeOnDelete();

            $table->foreignId('extraction_id')
                ->nullable()
                ->constrained('record_extractions')
                ->nullOnDelete();

            $table->text('description');

            // Who raised this issue — free text in Phase 1
            $table->string('raised_by')->nullable();

            $table->enum('status', [
                'open',
                'resolved',
                'carried_forward', // still unresolved, surfaced in next meeting
            ])->default('open');

            // Layer 2: chain — where did this issue first appear?
            $table->foreignId('carried_from_id')
                ->nullable()
                ->constrained('record_open_issues')
                ->nullOnDelete();

            // Layer 2: which record finally resolved this?
            $table->foreignId('resolved_in_record_id')
                ->nullable()
                ->constrained('organizational_records')
                ->nullOnDelete();

            $table->timestamps();

            // Layer 2 query: "all open issues for this org in last 6 months"
            $table->index(['record_id', 'status']);
        });
    }

    public function down(): void
    {
        // Drop in reverse order to respect foreign keys
        Schema::dropIfExists('record_open_issues');
        Schema::dropIfExists('record_action_items');
        Schema::dropIfExists('record_extractions');
        Schema::dropIfExists('organizational_records');
    }
};